name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]  # Change this to your default branch if it's not 'main'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Push to hub
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        # Get the last commit message
        COMMIT_MSG=$(git log -1 --pretty=format:"%s")
        
        # Initialize and configure git
        git init
        git remote add origin https://malanevans:$HF_TOKEN@huggingface.co/spaces/Agents-MCP-Hackathon/soccer-mcp-server
        
        # Add and commit with the last commit message
        git add .
        git commit -m "$COMMIT_MSG" || git commit -m "Deploy from GitHub Actions"
        
        # Push to Hugging Face Space
        git push https://malanevans:$HF_TOKEN@huggingface.co/spaces/Agents-MCP-Hackathon/soccer-mcp-server main

