name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]  # Change this to your default branch if it's not 'main'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Push to hub
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git push https://malanevans:$HF_TOKEN@huggingface.co/spaces/Agents-MCP-Hackathon/soccer-mcp-server main

